---
blueprint:
  name: Scene per Tag
  description: |
    # Scene per Tag

    This blueprint creates a automation that triggers when a tag is readed by
    a esphome tag reader. The automation will then call a scene.
    A nice Porject for an esphome tag reader is
    [Github - adonno/tagreader](https://github.com/adonno/tagreader)
  domain: automation
  input:
    tag_id:
      name: Tag
      description: The tag that triggers the scene
      selector:
        entity:
          domain: tag
    reader_id:
      name: Tag Reader
      description: The esphome tag reader that reads the tag
      selector:
        entity:
          domain: esphome
    scene_id:
      name: Scene
      description: The scene to call when the tag is readed
      selector:
        action:
          domain: scene

variables:
  tag_id: !input tag_id
  reader_id: !input reader_id
  scene_id: !input scene_id

trigger:
  platform: event
  event_type: esphome.tag_scanned

condition:
  condition: and
  conditions:
    - condition: template
      value_template: |
        "{{ trigger.event.data.device_id == reader_id.device_id }}"
    - condition: template
      value_template: |
        "{{ trigger.event.data.tag_id == tag_id.tag_id }}"

action:
  service: scene.turn_on
  target:
    entity_id: scene.scene_id
